### ISSUE TITLE
You don't need to do an EQU for the ORG address

### ISSUE THREAD

**Issue by spec-chum** [RetroCoderTV/RetroCoderASM-TV-ZX_Dev#1]
https://github.com/RetroCoderTV/RetroCoderASM-TV-ZX_Dev/blob/aba9d1c83ac472676833215753597e0987d0901d/Spikie%20Goes%20Skiing/sgs.asm#L1

You don't need to do it like that, you can use ORG at the top then a label called something like `START:` where your code starts, then at the end use `END START`

**Comment by RetroCoderTV** [comment]
I realise this. But i don't see any advantage for not having it
