### ISSUE TITLE
SJasm compiler options

### ISSUE THREAD

**Issue by mikroman** [RetroCoderTV/RetroCoderASM-TV-ZX_Dev#4]
[SJasm compile instructions.txt](https://github.com/RetroCoderTV/RetroCoderASM-TV-ZX_Dev/files/5235193/SJasm.compile.instructions.txt)

**Comment by mikroman** [comment]
bazinga.asm contains Pasmo directives incompatible with sjasm
this txt.file shows how anyone can compile with SJasm.

**Comment by RetroCoderTV** [comment]
nice one, will need this tomorrow when i try to use DeZog
